### ISSUE TITLE
Make columns.sccs less verbose

### ISSUE THREAD

**Issue by SebbeLar** [SebbeLar/Flex-Grid#1]
Instead of writing,

``` css
.col-1of2 {
  flex-basis: 50%;
}

.col-2of4 {
  flex-basis: 50%;
}
```

Do it like so,

``` css
.col-1of2,
.col-2of4 {
  flex-basis: 50%;
}
```
